version: '3'
services:
  web:
    build: .
    image: webapp7/webapp7:latest
    restart: always
    ports:
      - 8443:8443
    container_name: webapp7
    links:
      - db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/kiddyshouse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=webapp7

  db:
    container_name: webapp7DataBase
    image: mysql:5.7
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=webapp7
      - MYSQL_DATABASE=kiddyshouse