FROM maven as builder
COPY . /backend/
WORKDIR /backend
RUN mvn package


FROM openjdk:11-jre
COPY --from=builder /backend/target/*.jar /usr/app/
WORKDIR /usr/app
CMD [ "java", "-jar", "webapp7-0.0.1-SNAPSHOT.jar" ]