# Stage 1 Angular Production with node copying frontend to backend
FROM node:latest as node
COPY ./frontend/ /frontend/
WORKDIR /frontend
RUN npm install
RUN npm run build --prod -- --base-href='/new/'
# RUN ng run build
# RUN ng build --prod
# RUN npm install -g http-serve
# RUN echo %cd%

# RUN cp dist/frontend/* ../backend/src/main/resources/static/new/

# Stage 2 Springboot production with maven
FROM maven as builder
COPY ./backend/ /backend/
COPY --from=node /frontend/dist/frontend/ /backend/src/main/resources/static/new/
WORKDIR /backend
# RUN cd dist/frontend/
RUN mvn package

# Stage 3 Generating java jar
FROM openjdk:11-jre
COPY --from=builder /backend/target/*.jar /usr/app/
WORKDIR /usr/app
EXPOSE 8443
CMD [ "java", "-jar", "webapp7-0.0.1-SNAPSHOT.jar" ]

